spring:
  application:
    name: spring-academia-system
    version: @project.version@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sas
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret-key: cEB5QG0xOTg2MTI4X0BjQGRFbWlAX3NZc1RFbQ==
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
    skipped-endpoints:
      - /api/auth/login
      - /api/auth/users
      - /api/auth/refresh-token